#!/bin/bash

# default
if [ -z "$1" ]; then
    dir=$(date +"%Y/%d")
    mkdir -p $dir
    cat > $dir/aoc.py << EOF
#!/bin/python

# ======== setup ===========

from time import time
import sys
start = time()
data = open(sys.path[0] + "/data").read().split('\n')

# ======== code =======


print(f"\n===== {time() - start} sec =====")
EOF
    chmod +x $dir/aoc.py
    touch $dir/data
fi

# timings
if [ "$1" = "t" ]; then
    for file in $(find -name *.py)
    do
        echo
        echo "testing $file"
        time $file > /dev/null
    done
fi