#!/bin/bash

# default
if [ -z "$1" ]; then
    dir=$(date +"%Y/%d")
    mkdir -p $dir
    cat > $dir/idk.py << EOF
#!/bin/python

# ======== setup ===========
import sys
data = open(sys.path[0] + "/data").read().split('\n')

# ======== code =======

EOF
    chmod +x $dir/idk.py
    touch $dir/idk
fi

# timings
if [ "$1" = "t" ]; then
    for file in $(find -name *.py)
    do
        echo
        echo "testing $file"
        time $file > /dev/null
    done
fi